import Link from "next/link";

import { APP_CONFIG } from "@/config/app-config";

const { company, publicSite } = APP_CONFIG;

export function PrivacyPolicyContent() {
  return (
    <>
      <p>
        This Privacy Policy (“<strong>Policy</strong>”) describes how{" "}
        <strong>{company.legalName}</strong> (“<strong>GNUFOX</strong>”, “<strong>we</strong>”, “
        <strong>us</strong>”, or “<strong>our</strong>”), the owner and operator of the{" "}
        <strong>{publicSite.name}</strong> platform (the “<strong>Services</strong>”), collects,
        uses, stores, shares, and protects personal data. It also explains your rights and how to
        exercise them.
      </p>
      <p>
        The Services include, without limitation: (a) the Wasty customer mobile application
        (Android package identifier <code>com.mywasty.app</code> and any successor package); (b) the
        Wasty Partner collector mobile application; (c) this website and related public pages
        (including <code>{publicSite.domain}</code> and our Amplify / hosting domains); (d) the Wasty
        Admin / operations console; and (e) APIs, dashboards, SMS / OTP, maps, payments, and support
        channels that power waste collection, marketplace, rewards, and municipal reporting in India.
      </p>
      <p>
        By creating an account, verifying a phone number, using the apps or website, or otherwise
        providing personal data to us, you acknowledge that you have read this Policy. Where Indian
        law requires consent for a particular processing activity, we will seek that consent in a
        clear manner at the relevant point of collection.
      </p>
      <p>
        <strong>Important:</strong> This Policy is written for transparency and store-compliance
        (including Google Play and Apple App Store). It is not a substitute for independent legal
        advice. If you do not agree with this Policy, please do not use the Services.
      </p>

      <h2 id="controller">1. Data Fiduciary / Controller</h2>
      <p>
        For personal data processed in connection with the Services, the Data Fiduciary (controller)
        is:
      </p>
      <p>
        <strong>{company.legalName}</strong>
        <br />
        Brand / product: {publicSite.name}
        <br />
        Website:{" "}
        <a href={`https://${publicSite.domain}`} rel="noreferrer">
          https://{publicSite.domain}
        </a>
        <br />
        Privacy &amp; data requests:{" "}
        <a href={`mailto:${company.privacyEmail}`}>{company.privacyEmail}</a>
        <br />
        Support: <a href={`mailto:${company.supportEmail}`}>{company.supportEmail}</a>
        <br />
        Grievance / authorised contact for privacy queries:{" "}
        <a href={`mailto:${company.grievanceEmail}`}>{company.grievanceEmail}</a>
      </p>
      <p>
        Where we engage cloud or messaging providers to process data on our behalf, they act as Data
        Processors under our instructions, as described in Section 8.
      </p>

      <h2 id="scope">2. Scope and who this Policy applies to</h2>
      <p>This Policy applies to:</p>
      <ul>
        <li>
          <strong>Customers / households / businesses</strong> who schedule pickups, use bags/QR
          codes, buy from the marketplace, redeem rewards, or contact support;
        </li>
        <li>
          <strong>Partners / collectors / drivers</strong> who register, complete KYC, go online,
          accept jobs, upload proof, and request payouts;
        </li>
        <li>
          <strong>Staff / admin users</strong> authorised to use the operations console;
        </li>
        <li>
          <strong>Website visitors</strong> who browse public pages, including this Privacy Policy
          and Terms; and
        </li>
        <li>
          <strong>Government / municipal stakeholders</strong> who receive aggregated or authorised
          operational reports where such programmes are enabled.
        </li>
      </ul>
      <p>
        This Policy does not apply to third-party websites, stores, payment apps, or maps providers
        that have their own policies. Links to those services are for convenience only.
      </p>

      <h2 id="categories">3. Categories of personal data we collect</h2>
      <p>
        We collect only what is reasonably necessary for the Services. Depending on your role and
        features you use, this may include:
      </p>

      <h3>3.1 Identity and contact data</h3>
      <ul>
        <li>Full name or display name</li>
        <li>Mobile phone number (including country code; typically Indian +91 numbers)</li>
        <li>Email address (if provided)</li>
        <li>Account identifiers / user IDs generated by our systems</li>
        <li>Profile preferences (language, notification settings, avatar selections)</li>
      </ul>

      <h3>3.2 Authentication and security data</h3>
      <ul>
        <li>One-time passwords (OTPs) sent for login/verification (stored hashed / time-limited)</li>
        <li>Session tokens / JWTs and device push tokens</li>
        <li>Login timestamps, approximate device/app version, and security-related logs</li>
        <li>Admin authentication credentials or identity tokens for console access</li>
      </ul>

      <h3>3.3 Location and address data</h3>
      <ul>
        <li>
          Pickup / delivery addresses, landmarks, pin codes, and map pins (latitude / longitude)
        </li>
        <li>
          Approximate or precise device location when you grant permission (e.g., to confirm service
          area or pin a spot)
        </li>
        <li>
          For Partners: live / last-known location while marked Online, on shift, or on an active job,
          used for dispatch, ETA, and operational safety
        </li>
      </ul>

      <h3>3.4 Service, transaction, and operations data</h3>
      <ul>
        <li>Pickup schedules, waste types, bag counts / bag QR codes, job status history</li>
        <li>Orders, cart contents, payment method labels, invoices / order history</li>
        <li>Rewards points, redemptions, coupons, wallet-like balances</li>
        <li>Sell-waste / buy-back requests and related rates or estimates</li>
        <li>Support tickets, chat messages related to jobs, SOS / incident notes</li>
        <li>
          Partner KYC documents and metadata (e.g., ID, driving licence, vehicle registration —
          only as submitted for onboarding)
        </li>
        <li>Vehicle details, service zone, availability, ratings, payout requests and settlements</li>
        <li>Photos / images you capture for QR scanning, waste context, or collection proof</li>
      </ul>

      <h3>3.5 Device, diagnostics, and technical data</h3>
      <ul>
        <li>Device model, OS version, app version, crash / performance diagnostics</li>
        <li>IP address, approximate network info, and request logs for security and reliability</li>
        <li>
          Cookies or similar technologies on the website/admin console (session, preference, and
          security cookies). See Section 12.
        </li>
      </ul>

      <h3>3.6 Data we do not intentionally collect</h3>
      <ul>
        <li>
          We do not require microphone audio recording for core QR / proof features described in our
          store listings.
        </li>
        <li>
          We do not knowingly collect personal data of children under 18 (see Section 14).
        </li>
        <li>
          We do not sell personal data (see Section 9).
        </li>
      </ul>

      <h2 id="sources">4. How we collect personal data</h2>
      <ul>
        <li>
          <strong>Directly from you</strong> — registration, OTP login, profile forms, addresses,
          KYC uploads, support messages, camera captures you initiate.
        </li>
        <li>
          <strong>Automatically</strong> — when the apps/website run (device logs, approximate
          location if permitted, usage events needed to operate jobs and security).
        </li>
        <li>
          <strong>From Partners / Customers about each other</strong> — only what is needed to
          complete an assigned job (e.g., pickup address shared with the assigned Partner; job
          status shared with the Customer).
        </li>
        <li>
          <strong>From processors</strong> — e.g., SMS delivery status from OTP providers; map
          geocoding responses; cloud storage metadata.
        </li>
        <li>
          <strong>From authorised operators</strong> — admin users may enter or update operational
          records (assignments, settlements, catalog) in the console.
        </li>
      </ul>

      <h2 id="purposes">5. Purposes of processing (why we use your data)</h2>
      <p>We process personal data for the following purposes:</p>
      <ul>
        <li>
          <strong>Account creation and authentication</strong> — verify phone numbers via OTP,
          maintain sessions, prevent account takeover.
        </li>
        <li>
          <strong>Service delivery</strong> — schedule pickups, match Partners, navigate to pins,
          track job lifecycle, complete collections, and show history.
        </li>
        <li>
          <strong>Marketplace and rewards</strong> — fulfil orders, manage stock, calculate points,
          redeem rewards/coupons.
        </li>
        <li>
          <strong>Partner operations</strong> — KYC review, availability, routing, proof of
          collection, payouts and disputes.
        </li>
        <li>
          <strong>Customer support and safety</strong> — respond to tickets, SOS / incidents,
          quality and contamination notes.
        </li>
        <li>
          <strong>Communications</strong> — transactional SMS/OTP, in-app or push notifications
          about pickups, orders, and account security (you may control non-essential pushes in
          settings where available).
        </li>
        <li>
          <strong>Compliance and reporting</strong> — municipal / ESG / chain-of-custody reporting
          where programmes are enabled; tax, accounting, and legal obligations.
        </li>
        <li>
          <strong>Security, fraud prevention, and abuse detection</strong> — protect users,
          Partners, and infrastructure.
        </li>
        <li>
          <strong>Product improvement</strong> — diagnose crashes, measure feature reliability,
          improve maps/dispatch accuracy (using aggregated or de-identified insights where
          practicable).
        </li>
        <li>
          <strong>Legal claims</strong> — establish, exercise, or defend legal rights.
        </li>
      </ul>

      <h2 id="lawful-basis">6. Legal bases / grounds for processing (India)</h2>
      <p>
        Depending on the activity, we process personal data on one or more of the following grounds
        under applicable Indian law (including the Digital Personal Data Protection Act, 2023
        (“<strong>DPDP Act</strong>”) and rules, as they apply over time):
      </p>
      <ul>
        <li>
          <strong>Consent</strong> — e.g., precise location permission, camera access, optional
          marketing communications, certain KYC document uploads.
        </li>
        <li>
          <strong>Legitimate uses permitted by law</strong> — e.g., providing the service you
          requested (pickup / order fulfilment), employment-like Partner engagement records,
          medical emergencies / safety where applicable under law, employment of security measures,
          compliance with law or court orders, and other legitimate uses recognised under the DPDP
          Act.
        </li>
        <li>
          <strong>Contractual necessity</strong> — to perform our agreement with you (Terms of
          Service) and related transactions.
        </li>
      </ul>
      <p>
        Where processing is based on consent, you may withdraw consent with ease comparable to how
        it was given (for example, by disabling a permission in device settings, turning off a
        notification category, or contacting us). Withdrawal does not affect processing already
        lawfully completed, and may limit our ability to provide related features (e.g., without
        location we cannot pin your pickup accurately).
      </p>

      <h2 id="permissions">7. Device permissions (mobile apps)</h2>
      <p>Store listings and runtime prompts may request:</p>
      <ul>
        <li>
          <strong>Location</strong> — pin pickup addresses; Partner live tracking while Online / on
          job; service-area checks.
        </li>
        <li>
          <strong>Camera</strong> — scan bag/bin QR codes; capture collection or waste-related
          photos you choose to take.
        </li>
        <li>
          <strong>Notifications</strong> — pickup reminders, job updates, order status, security
          alerts.
        </li>
        <li>
          <strong>Network / storage</strong> — operate the app, cache content, upload images you
          submit.
        </li>
      </ul>
      <p>
        You can revoke permissions in your device settings. Some features will stop working without
        the related permission.
      </p>

      <h2 id="processors">8. Processors, subprocessors, and infrastructure</h2>
      <p>
        We use carefully selected service providers to operate Wasty. Categories include:
      </p>
      <ul>
        <li>
          <strong>Cloud hosting &amp; database</strong> — e.g., Amazon Web Services (API Gateway,
          Lambda, DynamoDB, S3, related services), typically with primary processing oriented to
          India / Asia regions where configured.
        </li>
        <li>
          <strong>Authentication / backend tooling</strong> — Google Firebase services where
          configured for identity, storage, or related features.
        </li>
        <li>
          <strong>SMS / OTP delivery</strong> — transactional SMS providers (e.g., Fast2SMS or
          similar) and/or telecom fallbacks for login codes.
        </li>
        <li>
          <strong>Maps &amp; geolocation</strong> — map tile providers and/or Google Maps Platform
          for maps, geocoding, and navigation context.
        </li>
        <li>
          <strong>Push notifications</strong> — Expo / platform push services when you enable
          notifications.
        </li>
        <li>
          <strong>Payments</strong> — payment service providers / UPI or card gateways if and when
          online payments are enabled (those providers process payment credentials under their own
          terms; we typically receive limited payment status metadata).
        </li>
        <li>
          <strong>Analytics / crash reporting</strong> — only if enabled, to improve stability.
        </li>
        <li>
          <strong>Customer support tooling</strong> — email and ticketing systems.
        </li>
      </ul>
      <p>
        Processors are bound by contracts / terms requiring them to process personal data only on
        documented instructions and to implement appropriate security. A current list of key
        subprocessors can be requested at{" "}
        <a href={`mailto:${company.privacyEmail}`}>{company.privacyEmail}</a>.
      </p>

      <h2 id="sharing">9. How we share personal data</h2>
      <p>We share personal data only as needed:</p>
      <ul>
        <li>
          <strong>Between Customer and assigned Partner</strong> — name/phone as needed, pickup
          address, waste type, bag info, and live job status so the job can be completed.
        </li>
        <li>
          <strong>With authorised GNUFOX / operator staff</strong> — ops, support, finance, and
          compliance roles with access controls.
        </li>
        <li>
          <strong>With processors</strong> — as in Section 8.
        </li>
        <li>
          <strong>With municipal / government programmes</strong> — where you or your city
          participates and disclosure is required or authorised (often aggregated; sometimes
          job-level chain-of-custody data).
        </li>
        <li>
          <strong>Corporate transactions</strong> — if we undergo a merger, acquisition,
          reorganisation, or asset sale, personal data may transfer subject to continuing
          confidentiality and notice where required.
        </li>
        <li>
          <strong>Legal requirements</strong> — to comply with law, regulation, legal process, or
          enforceable governmental request; to protect rights, safety, and property of GNUFOX,
          users, Partners, or the public.
        </li>
      </ul>
      <p>
        <strong>We do not sell personal data.</strong> We do not share personal data for
        third-party cross-context advertising of the type associated with “sale” / “share” under
        certain foreign privacy laws, because our core model is operational waste services—not ad
        brokerage.
      </p>

      <h2 id="transfers">10. International / cross-border transfers</h2>
      <p>
        Our primary intent is to process and store Service data in India or regions serving Indian
        users. Some processors (global cloud, maps, push, SMS) may process or back up data in other
        countries. Where cross-border transfer occurs, we take steps consistent with applicable
        Indian law and vendor contracts (including contractual safeguards and security
        requirements). By using the Services, you understand that such transfers may be necessary to
        operate global infrastructure components.
      </p>

      <h2 id="retention">11. Retention</h2>
      <p>We retain personal data only as long as needed for the purposes above, including:</p>
      <ul>
        <li>
          <strong>Account profile</strong> — for the life of the account, then deleted or
          anonymised after closure subject to legal holds.
        </li>
        <li>
          <strong>OTP records</strong> — short-lived (minutes), then expired / deleted.
        </li>
        <li>
          <strong>Partner live location history</strong> — short TTL for routing (often minutes to
          hours); last-known position may remain on the Partner profile while active.
        </li>
        <li>
          <strong>Jobs, orders, payouts, proof photos</strong> — typically up to{" "}
          <strong>24 months</strong>, or longer if required for disputes, audits, tax, municipal
          compliance, or legal claims.
        </li>
        <li>
          <strong>Security logs</strong> — for a limited period appropriate to investigate abuse.
        </li>
        <li>
          <strong>KYC documents</strong> — for as long as the Partner relationship continues and
          thereafter as required by law or fraud prevention.
        </li>
      </ul>
      <p>
        When retention ends, we delete, irreversibly anonymise, or aggregate data so it no longer
        identifies you, unless law requires otherwise.
      </p>

      <h2 id="cookies">12. Cookies and similar technologies (website / admin)</h2>
      <p>On websites and the admin console we may use:</p>
      <ul>
        <li>
          <strong>Strictly necessary cookies</strong> — authentication, security, load balancing.
        </li>
        <li>
          <strong>Preference cookies</strong> — language or UI preferences.
        </li>
        <li>
          <strong>Analytics cookies</strong> — only if enabled, to understand traffic and improve
          pages.
        </li>
      </ul>
      <p>
        You can control cookies through your browser settings. Blocking necessary cookies may break
        login.
      </p>

      <h2 id="security">13. Security</h2>
      <p>
        We implement reasonable security safeguards designed to prevent personal data breaches,
        including measures such as: encrypted transit (HTTPS/TLS), access controls and role-based
        permissions, credential hashing for OTPs, least-privilege cloud IAM, monitoring and logging,
        and vendor due diligence. No method of transmission or storage is 100% secure; you are
        responsible for keeping OTP codes and devices confidential.
      </p>
      <p>
        If a personal data breach occurs that requires notification under applicable law, we will
        notify affected users and/or authorities as required.
      </p>

      <h2 id="children">14. Children</h2>
      <p>
        The Services are intended solely for individuals who are <strong>18 years of age or
        older</strong>. We do not knowingly collect personal data from children. If you believe a
        minor has provided personal data, contact{" "}
        <a href={`mailto:${company.privacyEmail}`}>{company.privacyEmail}</a> and we will take steps
        to delete it promptly.
      </p>

      <h2 id="rights">15. Your rights (Data Principal rights)</h2>
      <p>
        Subject to the DPDP Act and other applicable law, you may have the right to:
      </p>
      <ul>
        <li>
          <strong>Access</strong> a summary of personal data being processed and the processing
          activities.
        </li>
        <li>
          <strong>Correction and completion</strong> of inaccurate or incomplete personal data.
        </li>
        <li>
          <strong>Erasure</strong> of personal data when it is no longer necessary for the stated
          purpose or when consent is withdrawn (subject to legal retention exceptions).
        </li>
        <li>
          <strong>Data portability</strong> of personal data provided by you, where applicable under
          law / product capability.
        </li>
        <li>
          <strong>Withdraw consent</strong> where processing is consent-based.
        </li>
        <li>
          <strong>Grievance redressal</strong> — complain to us, and thereafter to the Data
          Protection Board of India as provided under the DPDP Act.
        </li>
        <li>
          <strong>Nominate</strong> another individual to exercise rights in the event of death or
          incapacity, where the law provides.
        </li>
      </ul>
      <p>
        <strong>How to exercise rights:</strong> email{" "}
        <a href={`mailto:${company.privacyEmail}`}>{company.privacyEmail}</a> from your registered
        contact where possible, or use in-app Profile / account deletion flows. We may verify your
        identity before fulfilling requests. We will respond within timelines required by law
        (and otherwise within a reasonable period).
      </p>
      <p>
        <strong>Account deletion:</strong> Customers may request deletion from Profile where the
        feature is enabled, or by emailing us. Partners and admin users should contact support.
        Deletion may be delayed or partial where we must retain records for payouts, fraud
        prevention, municipal compliance, or legal obligations.
      </p>

      <h2 id="grievance">16. Grievance officer / contact for complaints</h2>
      <p>
        For privacy grievances related to the Services, contact:
      </p>
      <p>
        <strong>Grievance contact — {company.legalName}</strong>
        <br />
        Email: <a href={`mailto:${company.grievanceEmail}`}>{company.grievanceEmail}</a>
        <br />
        Also copy: <a href={`mailto:${company.privacyEmail}`}>{company.privacyEmail}</a>
      </p>
      <p>
        Please include your name, registered phone/email, description of the issue, and any job or
        order reference. We aim to acknowledge and address grievances in a timely manner. If
        unsatisfied after our response, you may escalate to the Data Protection Board of India as
        provided under applicable law.
      </p>

      <h2 id="automated">17. Automated decision-making</h2>
      <p>
        We may use automated systems for matching available Partners, ETA estimates, fraud signals,
        catalog ranking, or routing suggestions. These systems support operations; significant
        account actions (e.g., KYC rejection, suspension) involve human review processes where
        required by our policies. You may contact us to seek clarification about outcomes that
        materially affect you.
      </p>

      <h2 id="third-parties">18. Third-party links and app stores</h2>
      <p>
        Google Play, Apple App Store, payment apps, and map apps are governed by their own terms and
        privacy policies. When you download Wasty or complete a payment outside our direct card
        capture, those platforms may process data independently.
      </p>

      <h2 id="changes">19. Changes to this Policy</h2>
      <p>
        We may update this Policy to reflect product, legal, or operational changes. We will revise
        the “Last updated” date and, where changes are material, provide additional notice (in-app,
        website banner, or email/SMS) as appropriate. Continued use after the effective date
        constitutes acknowledgement of the updated Policy, except where consent is legally required
        for a new processing purpose.
      </p>

      <h2 id="governing-law">20. Governing law</h2>
      <p>
        This Policy is governed by the laws of India. Without prejudice to mandatory consumer or
        data-protection rights, disputes relating to privacy practices may be subject to the
        mechanisms in our Terms of Service and applicable law.
      </p>

      <h2 id="contact">21. Contact us</h2>
      <p>
        {company.legalName}
        <br />
        Product: {publicSite.name}
        <br />
        Privacy: <a href={`mailto:${company.privacyEmail}`}>{company.privacyEmail}</a>
        <br />
        Support: <a href={`mailto:${company.supportEmail}`}>{company.supportEmail}</a>
        <br />
        Grievance: <a href={`mailto:${company.grievanceEmail}`}>{company.grievanceEmail}</a>
        <br />
        Terms of Service: <Link href="/terms">/terms</Link>
      </p>
      <p className="text-muted-foreground text-sm">
        For Google Play / App Store listings, the canonical public Privacy Policy URL for Wasty is
        the Privacy page hosted on our official website / Amplify deployment linked from the
        homepage footer.
      </p>
    </>
  );
}

export const PRIVACY_TOC = [
  { id: "controller", label: "1. Data Fiduciary" },
  { id: "scope", label: "2. Scope" },
  { id: "categories", label: "3. Data we collect" },
  { id: "sources", label: "4. How we collect" },
  { id: "purposes", label: "5. Purposes" },
  { id: "lawful-basis", label: "6. Legal bases" },
  { id: "permissions", label: "7. Permissions" },
  { id: "processors", label: "8. Processors" },
  { id: "sharing", label: "9. Sharing" },
  { id: "transfers", label: "10. Transfers" },
  { id: "retention", label: "11. Retention" },
  { id: "cookies", label: "12. Cookies" },
  { id: "security", label: "13. Security" },
  { id: "children", label: "14. Children" },
  { id: "rights", label: "15. Your rights" },
  { id: "grievance", label: "16. Grievance" },
  { id: "automated", label: "17. Automation" },
  { id: "third-parties", label: "18. Third parties" },
  { id: "changes", label: "19. Changes" },
  { id: "governing-law", label: "20. Governing law" },
  { id: "contact", label: "21. Contact" },
] as const;
